- .gitignore
- src/client.rs
I didn't see a contributing doc in the repo so I am not sure the best way you want to take in contributions. I was able to work around this client side but you might want to consider trying to not leak `reqwest` internals out if you can help it.
> Adding a String constructor method for Client

- Cargo.toml
- DEVELOPING.md
- examples/tail.rs
- src/decode.rs
- src/lib.rs
This fixes a few bugs and places we weren't quite compliant with the spec:
* the handling for lines split across chunks wasn't quite right and could drop lines if that happened more than once in a stream.
* we were stripping all leading spaces from field values, instead of just the first leading space.
* multiple values for the same field would overwrite (now they concatenate instead)
* a line without a colon was treated as an error (now it treats the whole line as the field name, with an empty field value)
Closes #2 (includes commits from that PR, which included tests that discovered some of these bugs).
> [ch83910] Rewrite decoder to fix some decoding bugs

- src/client.rs
- src/decode.rs
- src/error.rs
By making the HttpRequest error type only yield status code type
failures, we can more easily take action on those errors in the SDK. For
other configuration related errors specific to request building, we have
introduced a new enum variant -- InvalidParameter.
> Make request errors more useful

- .circleci/config.yml
- Makefile
- contract-tests/src/bin/sse-test-api/main.rs
This PR enables the SSE test harness with an initial regex-based list of tests to skip. This will allow the step to pass in CircleCI.
We should eventually replace this with `-skip-from` functionality in the SSE test harness (which doesn't currently exist.)
Need https://github.com/launchdarkly/sse-contract-tests/pull/16 to be merged before the `-skip` parameters can be passed without issue.
> Enable SSE test harness in CircleCI job

- contract-tests/Cargo.toml
- contract-tests/src/bin/sse-test-api/stream_entity.rs
- eventsource-client/Cargo.toml
- eventsource-client/examples/tail.rs
- eventsource-client/src/client.rs
- eventsource-client/src/decode.rs
- eventsource-client/src/lib.rs
This draft hides the event source client's implementation (previously known as `Client`, now `ClientImpl`) behind a trait (known as `Client`).
This trait exposes only a `stream()` method, which is what `Client` exposed before.
My goal is to be able to add new functionality to Client without breaking changes for downstream users. 
The immediate need is for us to wrap whatever connector the user gives us in a `TimeoutConnector`, which allows us fine-grained control over read timeouts.
Previously, this would have been a breaking change, since the Client you get back from the builder would then be a `Client<TimeoutConnector<....>>`. 
I'm not sure that I've done this idiomatically, so please let me know if there are better ways to accomplish my goal.
Another way to do this would be to hide …
> Refactor Client to a trait

- Makefile
- contract-tests/src/bin/sse-test-api/main.rs
- eventsource-client/examples/tail.rs
- eventsource-client/src/client.rs
- eventsource-client/src/error.rs
- eventsource-client/src/event_parser.rs
- eventsource-client/test-data/persistent-event-id.sse
This PR causes the parser to ignore event IDs that contain null bytes. 
Additionally, it now persists event IDs into subsequent events that lack IDs.
This resolves two SSE test cases.
While making these changes, I encounter some difficulties since we were attempting to parse utf8 in a bunch of places.
I refactored to do utf8 parsing earlier in the process, which removes downstream parsing. 
Additionally, I simplified the unit tests to work with `&str` rather than `&[u8]` since SSE streams are UTF8.
Finally, I enabled a couple capabilities ('headers' and 'last-event-ids') that are now passing.
> Ignore invalid event IDs & persist existing event IDs

- eventsource-client/src/lib.rs
Downstream users wouldn't be able to reference the payload of an `event_parser::SSE::Event` (which is an `event_parser::Event`) because it wasn't exported. 
This makes it very inconvenient to try and handle the `SSE` enum properly.
This PR exports it in `lib.rs`.
> Make event_parser::Event public

- Makefile
- eventsource-client/src/client.rs
- eventsource-client/src/event_parser.rs
**Background**
- When reconnecting to an SSE stream, the `ReconnectingRequest` object passes along a `Last-Event-ID` header if the the server had sent one previously.
- `ReconnectingRequest` only sends the header when the ID isn't an empty string.
The event data objects that `ReconnectingRequest` receives are parsed from the raw data structure that the event_parser uses to keep track of the state. This parsing previously transformed an empty event ID into `None`, and non-empty into `Some(ID)`. 
**The bug**
Before this change, `ReconnectingRequest` only updated its own cache of the last event ID when the last event's ID was `Some(ID)`, as defined above. 
This logic is incorrect. `ReconnectingRequest` should always propagate the last known explicit event ID, which could
in fact be an empty …
> Propagate explicit empty event ID to ReconnectingRequest

- Makefile
- eventsource-client/src/client.rs
- eventsource-client/src/error.rs
This PR finishes off the last of the skipped contract tests, which was the 301 & 307 redirect handling.
It adds a new `FollowRedirects` state, which allows the client to follow the `Location` header sent by the server up to a maximum limit. 
Users can configure the limit using `ClientBuilder::redirect_limit`, but they cannot remove it entirely.
I've also added some new SSE tests to verify a couple edge cases (like missing Location header), which I'll put up for review on that repo.
https://github.com/launchdarkly/sse-contract-tests/pull/17
> Handle redirects with new FollowRedirects state

- contract-tests/src/bin/sse-test-api/main.rs
This capability was already implemented, but the test wasn't enabled (it passes.)
> Enable 'read-timeout' SSE contract test

- .circleci/config.yml
- eventsource-client/Cargo.toml
- eventsource-client/src/event_parser.rs
The `test-decode-line-split-across-chunks` unit test failed locally on M1 Mac with a panic due to `unwrap()`. It was not failing in CircleCi.
I then realized our CircleCi config was using the old rust image (`circleci/rust`), so I updated to `cimg/rust`, whereupon the test began failing as it did locally. 
Due to https://github.com/rust-lang/rust/pull/89825, `split_inclusive` now returns `None` when it used to return `Some(empty slice)` in our event parser.
The version of rust in `circleci/rust` is Rust 1.49.0, which is before the issue I linked above.
> Fix usage of split_inclusive in event parser

- .circleci/config.yml
- coverage.sh
Adds code coverage via `llvm-cov`, similar to the [server-sdk](https://github.com/launchdarkly/rust-server-sdk/blob/master/.circleci/config.yml#L27).
> Add code coverage step in CircleCi configuration

- contract-tests/src/bin/sse-test-api/main.rs
- eventsource-client/src/event_parser.rs
Comments are separate from other SSE events and should be emitted as
soon as they are received.
> Fix comment parsing logic

- .circleci/config.yml
- coverage.sh
Updates CircleCi image to `cimg/rust:1.60.0`. In this release of Rust, code coverage was stabilized, so the coverage generation script can be simplified.
[Current report.](https://output.circle-artifacts.com/output/job/203bd39d-ffba-4598-a69f-a7c7acb14a1a/artifacts/0/coverage/index.html)
[Previous report.](https://output.circle-artifacts.com/output/job/f8475b9f-5b27-4619-8450-141d93aa9a2d/artifacts/0/coverage/index.html
)
> Update to cimg/rust:1.60.0

- eventsource-client/src/client.rs
- eventsource-client/src/lib.rs
- eventsource-client/src/retry.rs
According to our streaming spec, default retry behavior should
continue with a backoff calculation until 60 seconds of continuous
failures have occurred, after which we can reset the retry interval.
While working on this task, I extracted the retry strategy into a
separate struct. This keeps the client a little cleaner, allows us to
actually unit test the retry policy, and will hopefully more easily
allow us to control the retry behavior for future unit tests.
> Reset retry backoff after max retry interval

- eventsource-client/Cargo.toml
- eventsource-client/src/client.rs
- eventsource-client/src/retry.rs
According to our streaming spec, the retry behavior should also include
some form of jitter. This jitter will cause the delay to be AT MOST
halved (e.g. a 30 second delay, post jitter will be in the range of
[15, 30] seconds).
> Add jitter support to retry behavior

- .circleci/config.yml
- contract-tests/src/bin/sse-test-api/main.rs
- contract-tests/src/bin/sse-test-api/stream_entity.rs
- eventsource-client/src/event_parser.rs
It looks like `time v0.3.20` has bumped its MSRV to 1.63, therefore we need to update it in CI if we wish to continue using it.
> chore: bump cimg/rust to 1.63.0

- eventsource-client/src/error.rs
This is necessary to make it work with error-wrapping libraries like [anyhow](https://crates.io/crates/anyhow) or [eyre](https://crates.io/crates/eyre). Of course it is also generally a good idea. ;-)
Please check if the error descriptions in the `Display` implementation are to your liking. The `impl<E> From<E> for Error` is unused and conflicts with `Error` implementing `std::error::Error` so I removed it.
> Make `Error` implement `std::fmt::Display`, `std::error::Error` and `Sync` 

- .circleci/config.yml
The contract tests require a secondary set of dependencies in order to spin up the required webserver. As a result, the required minimum rustc version might change independently of changes to our library.
Similarly, generating a code coverage report requires a unique set of crates as well.
To help with this, building the core library, generating coverage reports, and running the contract tests have been moved into separate CI jobs.
> ci: Separate CI steps

- .circleci/config.yml
- Cargo.toml
- contract-tests/Cargo.toml
- eventsource-client/Cargo.toml
- eventsource-client/src/client.rs
- eventsource-client/src/event_parser.rs
These version bumps bring our dependencies up to the latest versions.
This is technically a breaking change since we export the `HttpsConnector` from `hyper_rustls`, and the structure of that has changed. We now need to rely on the `HttpsConnectorBuilder`.
> deps!: Bump dependencies

- CODEOWNERS
I don't think DS Pipeline needs to review changes to this Rust library (which AFAIK is only used in the Rust SDK).
> Remove DS Pipeline from Rust eventsource CODEOWNERS

- contract-tests/src/bin/sse-test-api/main.rs
- contract-tests/src/bin/sse-test-api/stream_entity.rs
- eventsource-client/examples/tail.rs
- eventsource-client/src/client.rs
- eventsource-client/src/error.rs
- eventsource-client/src/event_parser.rs
- eventsource-client/src/lib.rs
- eventsource-client/src/response.rs
BEGIN_COMMIT_OVERRIDE
feat: Emit `SSE::Connected` event when stream is established (#79)
feat: Update `Error::UnexpectedResponse` to include failed connection details (#79)
END_COMMIT_OVERRIDE
> chore: Unify and merge customer contributions

- eventsource-client/src/client.rs
In the case where the SSE stream is available on connect and breaks mid-connection (e.g. because of server restart or network failure) and when polled in loop as such:
```rust
let es = es::ClientBuilder::for_url(
url,
)?
.reconnect(
es::ReconnectOptions::reconnect(true)
.delay(Duration::from_millis(500))
.delay_max(Duration::from_secs(20))
.retry_initial(false)
.build(),
)
.build();
let stream = es.stream();
loop {
let result = stream.next().await {}
}
```
The Client goes through following State transitions New -> Connecting -> Connected -> WaitingToReconnect -> New -> Connecting -> New -> Connecting -> New -> Connecting -> ....
It never waits for the delay_duration (this causes reconnects happening in about 1 ms rhythm), since it never goes to WaitingForReconnect again.
In client.rs on …
> fix: reconnect should use both reconnect and retry_initial for reconnection
